### ISSUE TITLE
Requirements-Description

### ISSUE THREAD

**Issue by Ben-Fitz** [cosc-499-EDG1/ethics-dashboard#17] opened 2021-10-07 18:34 UTC
A high-level description (about one paragraph) of the software you are building and who the target user groups are. Separately, explain how each user group is expected to use the software differently. (Recall that in order for two users to be considered as being in two different user groups, they must use the system differently either via a functional or non-functional system requirement.)

**Comment by michaeltt009** [comment] 2021-10-14 23:11
Duplicate of #18. Closing

**Closed by michaeltt009** 2021-10-14 23:11 UTC
Labels: task
